### ISSUE TITLE
Proposal to improve CSS styles

### ISSUE THREAD

**Issue by Rodro1975** [taxmeifyoucan/gfi#2]
Hello,

I've been reviewing the project and noticed that the `style.css` file could benefit from some design and presentation improvements. I would like to contribute by making adjustments to the CSS to improve the appearance of the project.

**Proposed Changes:**
- [ ] Review and improve the current design in `style.css`.
- [ ] Add styles to improve usability and visual appearance.
- [ ] Make sure the design is compatible with different devices.

Is there a specific aspect I should focus on or style guidelines I should follow? 

I appreciate any additional guidance. I am willing to discuss any details or receive feedback before starting to work on changes.

Thank you,
Rodrigo ORdoñez

**Comment by taxmeifyoucan** [comment]
Hey @Rodro1975, thanks for the interest in contributing here! 

The style of the website is generally driven by motherfuckingwebsite approach which means simple, readable and responsive. Some example can be found here https://github.com/lyoshenka/awesome-motherfucking-website. Generally I don't think there is need for other than minimal changes right now, unless there is some technical issue with the current style. 

@JoshDavisLight Is author of the style so he can provide some more feedback.

**Comment by Rodro1975** [comment]
I understand thanks for the comments
